apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  name: node-exporter
  namespace: prometheus
spec:
  clusterIP: None
  ports:
    - port: 9100
  selector:
    component: node-exporter
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: prometheus
spec:
  selector:
    matchLabels:
      component: node-exporter
  template:
    metadata:
      labels:
        component: node-exporter
    spec:
      hostNetwork: true
      hostPID: true
      containers:
        - name: node-exporter
          image: prom/node-exporter:v1.0.1
          args:
            - --path.rootfs=/host
          ports:
            - containerPort: 9100
          volumeMounts:
            - name: root
              mountPath: /host
              readOnly:  true
              mountPropagation: HostToContainer
      tolerations:
        - operator: Exists
      volumes:
        - name: root
          hostPath:
            path: /
